//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Project {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class LanguageInfoHelper : global::System.Configuration.ApplicationSettingsBase {
        
        private static LanguageInfoHelper defaultInstance = ((LanguageInfoHelper)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LanguageInfoHelper())));
        
        public static LanguageInfoHelper Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PHP")]
        public string php {
            get {
                return ((string)(this["php"]));
            }
            set {
                this["php"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ASP.NET")]
        public string aspx {
            get {
                return ((string)(this["aspx"]));
            }
            set {
                this["aspx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Perl")]
        public string perl {
            get {
                return ((string)(this["perl"]));
            }
            set {
                this["perl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Python")]
        public string python {
            get {
                return ((string)(this["python"]));
            }
            set {
                this["python"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nothing")]
        public string empty {
            get {
                return ((string)(this["empty"]));
            }
            set {
                this["empty"] = value;
            }
        }
    }
}
